services:
  streamlit:
    image: python:3.9-slim
    container_name: streamlit_app
    working_dir: /app
    volumes:
      - .:/app
    command: streamlit run app.py --server.address=0.0.0.0
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_APP=app.py
    restart: unless-stopped
    labels:
      coolify.service: "true"
      coolify.project: "streamlit"
