name: plannotate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - click
  - curl
  - numpy
  - biopython>=1.78
  - blast>=2.10.1
  - diamond>=2.0.13
  - pandas>=1.3.5
  - python>=3.7
  - ripgrep>=13.0.0
  - streamlit>=1.8.1
  - tabulate>=0.8.9
  - trnascan-se>=2.0.7
  - bokeh=2.4.1
