name: pLannotate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - diamond=2.0.0
  - trnascan-se=2.0.7
  - tabulate=0.8.9
  - blast=2.10.1
  - streamlit=0.78.0
  - biopython=1.78
  - bokeh=2.2.1
  - ripgrep=13.0.0
