name: plannotate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython >1.77
  - bokeh=2.4.1
  - click=7.1.2
  - curl
  - blast >=2.10.1
  - diamond >=2.0.13
  - numpy
  - pandas
  - python >=3.7
  - ripgrep >=13.0.0
  - streamlit=1.2.0
  - tabulate >=0.8.9
  - trnascan-se >=2.0.7