name: plannotate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7
  - diamond=2.0.13
  - trnascan-se=2.0.7
  - tabulate=0.8.9
  - blast=2.10.1
  - streamlit=1.2.0
  - biopython=1.78
  - bokeh=2.4.1
  - ripgrep=13.0.0
