name: Python Package using Conda

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: true
        environment-file: environment.yml
    - run: |
        pytest --version
        pytest
      shell: micromamba-shell {0}